const puppeteer = require('puppeteer')
;(async () => {
  const b = await puppeteer.launch({ headless:'new', args:['--no-sandbox'] })
  const p = await b.newPage()
  p.on('pageerror', e => console.log('[pageerror]', String(e).slice(0,300)))
  p.on('console', m => { if (m.type()==='error') console.log('[err]', m.text().slice(0,250)) })
  p.on('requestfailed', r => console.log('[failed]', r.url().split('/').pop(), r.failure()?.errorText))
  await p.setViewport({width:1440,height:900})
  await p.goto('http://localhost:3111/', { waitUntil:'networkidle0' })
  await new Promise(r=>setTimeout(r,3000))
  console.log('backdrop:', await p.evaluate(()=>{const e=document.querySelector('[data-hero-backdrop]');return e?e.getAttribute('data-canvas-active'):'NO BACKDROP'}))
  console.log('canvas:', await p.evaluate(()=>!!document.querySelector('[data-hero-canvas] canvas')))
  await b.close()
})()
