import puppeteer from 'puppeteer'
const browser = await puppeteer.launch({ headless: true })
const page = await browser.newPage()
await page.setViewport({ width: 390, height: 844, deviceScaleFactor: 2, isMobile: true, hasTouch: true })
await page.goto('http://localhost:3000', { waitUntil: 'networkidle0' })
await new Promise(r => setTimeout(r, 1500))
await page.screenshot({ path: './temporary screenshots/menu-cookie.png' })
await page.evaluate(() => { const b=[...document.querySelectorAll('button')].find(x=>/Akceptuję/.test(x.textContent)); b && b.click() })
await new Promise(r => setTimeout(r, 600))
await page.evaluate(() => { const b=[...document.querySelectorAll('button')].find(x=>/Otwórz menu/.test(x.getAttribute('aria-label')||'')); b && b.click() })
await new Promise(r => setTimeout(r, 700))
await page.screenshot({ path: './temporary screenshots/menu-open.png' })
console.log('done')
await browser.close()
